# NumPy Arrays, Array Creation, Indexing & Slicing

# Import NumPy

NumPy is the backbone of AI, Machine Learning, Deep Learning, Pandas and Scikit-learn.

In [1]:
# Import NumPy library
import numpy as np

# Display installed version
print("NumPy Version:", np.__version__)

NumPy Version: 1.26.4


# Creating Arrays

Arrays store homogeneous data efficiently.

In [10]:
# Create a 1D array
arr = np.array([10,20,30,40])

# Print the array
print(arr)

[10 20 30 40]


In [11]:
# Create a 2D array (matrix)
matrix = np.array([[1,2,3],
                   [4,5,6]]) # 2 square bracket - 2d array

# Print the matrix
print(matrix)

[[1 2 3]
 [4 5 6]]


# Different Array Creation Methods

Frequently used functions for creating arrays.

In [12]:
# Matrix of zeros
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Matrix of ones
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Sequence using arange
print(np.arange(1,11,2))

[1 3 5 7 9]


In [16]:
# Evenly spaced values
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [17]:
# Random integers
print(np.random.randint(1,100,(3,3)))

[[ 7 51 63]
 [11  5 21]
 [30 15 53]]


# Array Properties

Understanding array properties is important for ML.

In [18]:
# Create sample matrix
data=np.array([[10,20,30],[40,50,60]])

# Shape
print(data.shape)

(2, 3)


In [19]:
# Dimensions
print(data.ndim)

2


In [20]:
# Total elements
print(data.size)

6


In [21]:
# Datatype
print(data.dtype)

int32


In [22]:
# Bytes per element
print(data.itemsize)

4


In [23]:
# Total memory
print(data.nbytes)

24


# Indexing

Indexing retrieves individual elements.

In [24]:
# Create array
numbers=np.array([5,10,15,20,25])

# First element
print(numbers[0])

5


In [25]:
# Last element
print(numbers[-1])

25


In [46]:
# Create matrix
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

# Row 2 Column 3
print(mat[1,2])

6


In [47]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# Row 3 Column 1
print(mat[2,0])

7


# Slicing

Slicing extracts subsets of data.

In [28]:
# Create array
values=np.array([10,20,30,40,50,60,70])

# Slice index 1 to 4
print(values[1:5])

[20 30 40 50]


In [29]:
# First four values
print(values[:4])

[10 20 30 40]


In [30]:
# Values from index 3
print(values[3:])

[40 50 60 70]


In [31]:
# Reverse array
print(values[::-1])

[70 60 50 40 30 20 10]


In [32]:
# Create matrix
matrix=np.arange(1,17).reshape(4,4)

# Print matrix
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [33]:
# Top-left block
print(matrix[:2,:2])

[[1 2]
 [5 6]]


In [34]:
# Second column
print(matrix[:,1])

[ 2  6 10 14]


In [35]:
# Middle block
print(matrix[1:3,2:4])

[[ 7  8]
 [11 12]]


# Boolean Indexing

Useful for filtering ML datasets.

In [36]:
# Salary values
salary=np.array([25000,45000,35000,70000,55000])

# Condition
condition=salary>40000

# Print Boolean result
print(condition)

[False  True False  True  True]


In [37]:
# Print filtered salaries
print(salary[condition])

[45000 70000 55000]


# Fancy Indexing

Select multiple positions together.

In [8]:
# Create array
arr=np.array([100,200,300,400,500])

# Select index positions
print(arr[[0,2,4]])

[100 300 500]


# Machine Learning Example

Separate features and target.

In [39]:
# Create sample dataset
dataset=np.array([
[22,25000,0],
[30,50000,1],
[28,42000,1],
[35,65000,0]
])

# Feature columns
X=dataset[:,:2]

# Target column
y=dataset[:,2]

# Print X
print(X)

[[   22 25000]
 [   30 50000]
 [   28 42000]
 [   35 65000]]


In [38]:
# Print y
print(y)

[0 1 1 0]
